# minimum supported version
FROM python:3.10-slim-bookworm

WORKDIR /django-atris

ADD ./.pre-commit-config.yaml /django-atris/
ADD ./ruff.toml /django-atris/

RUN apt-get -y update && \
    apt-get -y install git && \
    git init && \
    pip install pre-commit==4.6.2 && \
    pre-commit install --install-hooks

RUN git config --global --add safe.directory /django-atris
