# Generated by Django 4.2.26 on 2025-11-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atris', '0010_alter_archivedhistoricalrecord_additional_data_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='archivedhistoricalrecord',
            new_name='atris_archi_object__ddf5a5_idx',
            old_fields=('object_id', 'history_date'),
        ),
        migrations.RenameIndex(
            model_name='historicalrecord',
            new_name='atris_histo_object__16921f_idx',
            old_fields=('object_id', 'history_date'),
        ),
    ]
