# Generated by Django 5.2.13 on 2026-06-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atris', '0011_rename_archivedhistoricalrecord_object_id_history_date_atris_archi_object__ddf5a5_idx_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='archivedhistoricalrecord',
            index=models.Index(fields=['content_type', '-history_date'], name='atris_archi_content_38d097_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalrecord',
            index=models.Index(fields=['content_type', '-history_date'], name='atris_histo_content_513802_idx'),
        ),
    ]
