name: Test and publish django-atris to pypi

on: workflow_dispatch

jobs:
  run-tests:
    uses: ./.github/workflows/tests.yaml
  call-publish:
    uses: ./.github/workflows/publish.yaml
    needs: run-tests
    with:
      TWINE_USERNAME: ${{ secrets.PROD_TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.PROD_TWINE_PASSWORD }}
