name: Publish

on:
  workflow_call:
    secrets:
      TWINE_USERNAME:
        required: true
      TWINE_PASSWORD:
        required: true
      TWINE_REPOSITORY:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Upload package
        run: |
          pip install --upgrade pip
          pip install --upgrade twine
          pip install --upgrade build
          python3 -m build
          python3 -m twine upload dist/*
