name: Publish
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Upload package
        run: |
          sudo rm -rf dist src/django_atris.egg-info/ .coverage
          pip install --upgrade pip
          pip install --upgrade twine
          pip install --upgrade build
          python3 -m build
          python3 -m twine upload dist/*
