name: Publish

on:
  workflow_call:
    inputs:
      TWINE_USERNAME:
        required: true
        type: string
      TWINE_PASSWORD:
        required: true
        type: string
      TWINE_REPOSITORY:
        required: false
        type: string
        default: 'testpypi'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: ${{ inputs.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ inputs.TWINE_PASSWORD }}
      TWINE_REPOSITORY: ${{ inputs.TWINE_REPOSITORY }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Upload package
        run: |
          pip install --upgrade pip
          pip install --upgrade twine
          pip install --upgrade build
          env | grep TWINE_REPOSITORY
          python3 -m build
          python3 -m twine upload dist/*
