name: TEST and push to test.pypi.org

on:
  workflow_dispatch:
  push:
    branches: [ master ]

concurrency: master-${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
#    env:
#      TWINE_USERNAME: ${{ secrets.TEST_TWINE_USERNAME }}
#      TWINE_PASSWORD: ${{ secrets.TEST_TWINE_PASSWORD }}
#      TWINE_REPOSITORY_URL: ${{ secrets.TEST_TWINE_REPOSITORY_URL }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          docker-compose down
          docker-compose run --rm test_py36
          docker-compose down
          docker-compose run --rm test_py37
          docker-compose down
          docker-compose run --rm test_py38
          docker-compose down

      - name: Publish test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path:
            test-results_*
        if: ${{ always() }}
